services:
  - attributes:
      name: 'Médecins de Monde, Paris'
      address: ''
      phone: ''
      mail: ''
      link: ''
      user_id: ""
      ngo_id: ''
    activity_slots:
      - attributes:
          title: ""
          opening_hours: ""
          activities: ""
          price: ""
          appointment: false
          start_date: ""
          end_date: ""
        categories:
          - id: ''
          - id: ''
        beneficiaries:
          - id: ''
          - id: ''
          - id: ''
  - attributes:
      name: 'Médecins de Monde, Paris'
      address: ''
      phone: ''
      mail: ''
      link: ''
      user_id: ""
      ngo_id: ''
    activity_slots:
      - attributes:
          title: ""
          opening_hours: ""
          activities: ""
          price: ""
          appointment: false
          start_date: ""
          end_date: ""
        categories:
          - name: ''
          - name: ''






[{ user_id: 1, ngo_id: 1, mail: "ile-de-france@medecinsdumonde.net", link: "https://www.medecinsdumonde.org/fr/contact/ile-de-france", name: , address: "15 boulevard de Picpus 75012 Paris", phone:"0143148181" },
    { user_id: 1, ngo_id: 1, link: "https://www.medecinsdumonde.org/fr/contact/auvergne-rhone-alpes-0", name: 'Médecins de Monde, Plaine-Saint-Denis', address: "8/10 rue des blés - 93210 La Plaine-Saint-Denis", phone: "0155931932" },
    { user_id: 1, ngo_id: 3, mail: "lestremplins@restosducoeur.org", link: "https://www.restosducoeur.org/associations-departementales/les-tremplins-des-restaurants-du-coeur-relais-du-coeur/", name: 'LES TREMPLINS DES RESTAURANTS DU CŒUR', address: "42 Rue de Clichy, 75009 Paris", phone: "0987335391" },
    { user_id: 1, ngo_id: 3, link:"http://hauts-de-seine.restosducoeur.org/liste-des-centres/asnieres/", name: 'Restos du Coeur Asnières', address: "4 rue Louis Armand, 92600 Asnières sur Seine", phone: "0967023824" },
    { user_id: 1, mail: "example@ngo.com", link: "https://www.medecinsdumonde.org/fr/contact/auvergne-rhone-alpes-0", name: 'ClothRestauduCoeur', address: "42 Rue de Clichy, 75009 Paris", phone: "0650166564" },
    { user_id: 1, mail: "example@ngo.com", link: "https://www.medecinsdumonde.org/fr/contact/auvergne-rhone-alpes-0", name: 'FooMigrants', address: "9 rue Edouard-Jacques, 75014 Paris", phone: "0650166564" }
]


activities = [[["showers"], { service_id: 1, title: 'Douches gratuites', opening_hours: "Lundi au Vendredi, de 9h a 13h et de 14h a 18h", appointment: false, price: "0"}],
    [["showers"], { service_id: 2, title: 'Douches gratuites', opening_hours: "Lundi au Vendredi, de 9h a 13h et de 14h a 18h", appointment: false, price: "0"}],
    [['legal','showers'], { service_id: 3, title: 'Assistance juridique', opening_hours: "Lundi au Vendredi, de 9h a 13h et de 14h a 18h", appointment: false, price: "10"}],
    [["food"], { service_id: 4, title: 'Centre Bébés', opening_hours: "Mardi de 9h00 à 11h30 et de 13h30 à 16h00", appointment: false}],
    [["food"], { service_id: 4, title: 'Centre Adultes', opening_hours: "Lundi de 13h30 à 16h30 et Jeudi de 9h30 à 11h30 & 13h30 à 16h00", appointment: false}],
    [["clothes"], { service_id: 5, title: 'Vestiaire', opening_hours: "Lundi au Vendredi, de 9h a 13h et de 14h a 18h", appointment: false}],
    [["daycare"], { service_id: 6, title: 'Vestiaire', opening_hours: "Lundi au Vendredi, de 9h a 13h et de 14h a 18h", appointment: false}],
    [["food", "clothes"], { service_id: 6, title: 'Distribution alimentaire', opening_hours: "Lundi au Vendredi, de 9h à 13h et de 14h a 18h", appointment: false, price: "0"}]
]
